apiVersion: v1
kind: Service
metadata:
  annotations:
    api.service.kubernetes.io/path: /undertowTest
  name: demo-service 
spec:
  selector:
    app: fuse74-camel-twitter
  ports:
    - name: undertow-port
      port: 9956
      targetPort: 9956

